import { NextResponse } from "next/server";
import connectDB from "@/lib/mongodb";
import Booking from "@/Models/Booking";
import PromoCode from "@/Models/PromoCode";

export async function POST(req: Request) {
  try {
    await connectDB();

    const data = await req.json();
    const {
      experienceId,
      experienceTitle,
      experienceLocation,
      slotId,
      date,
      dateRaw,
      timeSlot,
      userName,
      userEmail,
      userPhone,
      numberOfPeople,
      subtotal,
      promoCode,
      discount = 0,
      finalPrice,
    } = data;

    // 🧾 Optional: Validate promo code before saving
    let appliedDiscount = discount;
    let message = "Booking created successfully";

    if (promoCode) {
      const promo = await PromoCode.findOne({ code: promoCode.toUpperCase() });
      if (promo) {
        const result = promo.validatePromo(subtotal);
        if (result.valid) {
          appliedDiscount = result.discount;
          message = result.message;
        }
      }
    }

    // 🧠 Create new booking — referenceId auto-generated by the schema
    const booking = await Booking.create({
      experienceId,
      experienceTitle,
      experienceLocation,
      slotId,
      date,
      dateRaw,
      timeSlot,
      userName,
      userEmail,
      userPhone,
      numberOfPeople,
      subtotal,
      promoCode: promoCode?.toUpperCase(),
      discount: appliedDiscount,
      finalPrice: subtotal - appliedDiscount,
    });

    return NextResponse.json({
      success: true,
      message,
      data: booking,
    });
  } catch (err) {
    console.error("Booking creation error:", err);
    return NextResponse.json(
      { success: false, message: "Server error" },
      { status: 500 }
    );
  }
}
